# params.yaml
data:
  raw_path: data/raw/iris.csv

train:
  test_size: 0.2
  random_state: 42
  max_iter: 200
  C: 1.0
  solver: lbfgs
  experiment_name: mlops_demo_experiment
  autolog: true      # set false to disable autologging
